"""
File: alert_log_repository.py

Purpose:
Handles all database queries for the alert_log table, providing
filtered access to historical alert events generated by the
sensor threshold logic.

Responsibilities:
- Query the alert_log table with optional filters for site, date
  range, and severity level
- Return ordered alert history with a configurable result limit
- Keep database query logic separate from business logic in services

Layer:
Backend (Repository / Data Access)

Related:
- alert_log.py in models (the table being queried)
- researcher_dashboard_router.py (calls this to expose alert history)
- sensor_reading_repository.py (sensor data that generates the alerts)
- seed_sensor_readings.py (populates the alert_log table with initial data)
- researcher.js (displays alert history and filters on the researcher dashboard)
"""

from sqlalchemy.orm import Session
from app.models.alert_log import AlertLog


def get_alert_history(
    db: Session,
    site_id: str | None = None,
    start_date: str | None = None,
    end_date: str | None = None,
    severity: str | None = None,
    limit: int = 100,
) -> list[AlertLog]:
    """
    returns alert history from alert_log table
    """

    query = db.query(AlertLog)

    if site_id:
        query = query.filter(AlertLog.site_id == site_id)

    if start_date:
        query = query.filter(AlertLog.timestamp >= start_date)

    if end_date:
        query = query.filter(AlertLog.timestamp <= end_date)

    if severity:
        query = query.filter(AlertLog.severity == severity)

    return query.order_by(AlertLog.timestamp.desc()).limit(limit).all()